version: "3.3"

volumes:
  volume-mariadb:
  volume-wordpress:

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - volume-mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - volume-wordpress:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - volume-wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always


networks:
  inception: