version: "3.3"

volumes:
  volume-mariadb:
  volume-wordpress:

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - volume-mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
    env_file:
      - .env

  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx
  #   volumes:
  #     - volume-wordpress:/var/www/html
  #   ports:
  #     - 443:443
  #   restart: always
  #   networks:
  #     - inception
  #   env_file:
  #     - .env

  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress
  #   volumes:
  #     - volume-wordpress:/var/www/html
  #   ports:
  #     - 9000:9000
  #   restart: always
  #   networks:
  #     - inception
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mariadb


networks:
  inception:
    driver: bridge