version: "3.9"

services:
  mariadb:
    build:
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    volumes:
      -volumeName:containerPath:ro
    ports:
      - 3306:3306
    restart: unless-stopped

  nginx:
    image:
    container_name: nginx
    volumes:
      -volumeName
    ports:
      - 443:443
    restart: unless-stopped

  wordpress:
    image:
    container_name: wordpress
    volumes:
     - vol
    ports:
      - 9000:9000
