version: "3.3"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    volumes:
      - volume-mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - volume-wordpress:/usr/share/nginx/html
    ports:
      - 443:443
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - volume-wordpress:/usr/share/nginx/html
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception
    env_file:
      - .env

  networks:
      inception:
        driver: bridge

  volumes:
    volume-mariadb:
    driver: local
    driveropts:
      type: 'none'
      o: 'bind'
      device: /home/yst-laur/data/database

    volume-wordpress:
      driver: local
      driveropts:
        type: 'none'
        o: 'bind'
        device: /home/yst-laur/data/wordpress