version: "3.3"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - volume-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - volume-wordpress:/var/www/html
    ports:
      - 443:443
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - volume-wordpress:/var/www/html
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception
    env_file:
      - .env

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/yst-laur/data/database

  volume-wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/yst-laur/data/wordpress

networks:
  inception:
    driver: bridge