version: "3.3"


services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - volume-mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - volume-wordpress:/var/www/
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - volume-wordpress:/var/www/
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb
  volume-wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  inception: