version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    volumes:
      -volumeName:containerPath:ro
    ports:
      - 3306:3306
    restart: always
    networks:
      - cont_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      -volumeName
    ports:
      - 443:443
    restart: always
    networks:
      - cont_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
     - vol
    ports:
      - 9000:9000
    restart: always
    networks:
      - cont_net

  networks:
    
