#!bin/sh

set -e

sleep 5

echo running wp core download...
wp core download --force --allow-root --path=/var/www/
echo wp core download done...

echo running wp core config...
wp config create --allow-root --path=/var/www --dbname=$WORDPRESS_DB_NAME --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=$WORDPRESS_DB_HOST --dbcharset=utf8 --dbcollate=utf8_general_ci
echo config file created...
wp core config --allow-root --path=/var/www/ --dbname=$WORDPRESS_DB_NAME --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=$WORDPRESS_DB_HOST
echo wp core config done...

echo wp core install running...
wp core install --allow-root --path=/var/www/ --url=localhost --title="Inception" --admin_user=$WORDPRESS_SUPER_USER --admin_password=$WORDPRESS_SUPER_USER_PASS --admin_email=admin@example.com
echo wp core install done...

echo creating user...
wp 	user create --allow-root $WP_USER $WP_USER_EMAIL --role=author --user_pass=$WP_USER_PASS --path="/var/www/"
echo user created...

echo changing directory ownership...
chown -R www-data:www-data /var/www/

exec $@