#!bin/bash

set -e

while ! ping -c 1 -n mariadb &> /dev/null
do
	sleep 1;
done
if test -f "/var/www/wp-config.php";
then
	echo Skipping creation...
else
	echo running wp core download...
	wp core download --force --allow-root --path=/var/www/
	echo wp core download done...

	echo running wp core config...
	wp core config --allow-root --path=/var/www/ --dbname=$WORDPRESS_DB_NAME --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=$WORDPRESS_DB_HOST
	echo wp core config done...

	echo wp core install running...
	wp core install --allow-root --url=yst-laur.42.fr --path=/var/www/ --title="Inception" --admin_user=$WORDPRESS_ADMIN --admin_password=$WORDPRESS_ADMIN_PASS --admin_email=admin@example.com --skip-email
	echo wp core install done...

	echo creating user...
	wp 	user create --allow-root $WP_USER $WP_USER_EMAIL --role=author --user_pass=$WP_USER_PASS --path="/var/www/"
	echo user created...

	echo changing directory ownership...
	chown -R www-data:www-data /var/www/
fi

echo Launching php-fpm7...
exec php-fpm7 -F